### ISSUE TITLE
Practica #5

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-abicoronel#3]
[PRACTICA5 (1).pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-abicoronel/files/8376765/PRACTICA5.1.pdf)

**Comment by SANDRAVELASCO** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
