### ISSUE TITLE
diseño de control para cajas de texto

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-abicoronel#4]
[PRACTICA5.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-abicoronel/files/8873640/PRACTICA5.pdf)

**Comment by ang3-l32** [comment]
calificacion:20

**Comment by josealfredo79** [comment]
bien hecho y revisado
